sudo: false


language: java

jdk:
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
  - $HOME/protobuf
  - $HOME/.m2

before_install:
  - ./scripts/install-protobuf.sh
  - export PATH=$PATH:$HOME/protobuf/bin
