sudo: false

dist: xenial

addons:
  apt:
    packages:
      - protobuf-compiler

language: java

jdk:
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
  - $HOME/.m2

before_install:
  - ./scripts/install-protobuf.sh
  - export PATH=$PATH:$HOME/protobuf/bin
